export const UPDATE_POINTS = 'UPDATE_POINTS';
export const UPDATE_PUZZLE_COLON_INFO = 'UPDATE_PUZZLE_COLON_INFO';
export const UPLOAD_FILE = 'UPLOAD_FILE';
export const UPDATE_FILE_INFO = 'UPDATE_FILE_INFO';
export const UPDATE_PROGRESS_VAL = 'UPDATE_PROGRESS_VAL';