export const UPDATE_POINTS = 'UPDATE_POINTS';
export const UPDATE_PUZZLE_COLON_INFO = 'UPDATE_PUZZLE_COLON_INFO';
export const UPLOAD_FILE = 'UPLOAD_FILE';
export const UPDATE_PREVIEW_IMAGE = 'UPDATE_PREVIEW_IMAGE';